DELIMITER $$
CREATE PROCEDURE SP_USER_LOGOUT(
IN user_ID INT
)
BEGIN 

   SET @USER_ID = (SELECT USR.USER_ID FROM USERS AS USR WHERE USR.USER_ID=user_ID);
   SET @LOGIN_COUNT = (SELECT USR.LOGIN_COUNT FROM USERS AS USR WHERE USR.USER_ID=user_ID);
   
    IF(@LOGIN_COUNT > 0 && USER_ID <> 0 ) THEN
             UPDATE USERS AS U SET U.LOGIN_COUNT = U.LOGIN_COUNT-1 WHERE U.USER_ID = user_ID;
             SELECT 'true' AS SUCCESS,@USER_ID AS USER_ID,'Sucessfull Logout' AS ERROR_DESC;
	ELSE 
          IF(@LOGIN_COUNT = 0) THEN
             SELECT 'false' AS SUCCESS,@USER_ID AS USER_ID,'Please login first to logout' AS ERROR_DESC;
		  ELSE
             SELECT 'false' AS SUCCESS,@USER_ID AS USER_ID,'Invalid User Id' AS ERROR_DESC;
		  END IF;
	END IF ;
END$$
DELIMITER ;
