DELIMITER $$
CREATE PROCEDURE SP_UPDATE_USER_DETAILS(
IN user_id      INT,
IN Country  VARCHAR(300),
IN State   VARCHAR(300),
IN City  VARCHAR(300),
IN Profile_picture_url VARCHAR(300)
)
BEGIN 
   
   SET @USER_ID = (SELECT U.USER_ID FROM USERS AS U WHERE U.USER_ID=user_id);
   
   IF (@USER_ID IS NOT NULL) THEN 
            
            SET @CID = (SELECT C.COUNTRY_ID FROM COUNTRY_MASTER AS C WHERE COUNTRY_NAME=Country);
            SET @SID = (SELECT S.COUNTRY_ID FROM STATE_MASTER AS S WHERE STATE_NAME=State);
            SET @CITYID = (SELECT CY.CITY_ID FROM CITY_MASTER AS CY WHERE CITY_NAME=City);
            
            UPDATE USER_DETAILS AS UD SET UD.COUNTRY_ID=@CID,UD.STATE_ID=@SID,UD.CITY_ID=@CITYID,UD.PROFILE_PICTURE_URL=Profile_picture_url WHERE UD.USER_ID=user_id;
            
            SELECT 'true' AS SUCCESS,@USER_ID AS USER_ID,'Successfully Updated' as ERROR_DESC; 
   ELSE
            SELECT 'false' AS SUCCESS,0 AS USER_ID,'Invalid User_Id' as ERROR_DESC; 
   END IF;
   
END$$
DELIMITER ;
